name: 'Notification'
description: 'Send GitHub Actions pipelines status to Discord.'
inputs:
  webhook_url:
    description: 'Discord webhook URL'
    required: true
runs:
  using: 'node10'
  main: 'dist/index.js'